[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20170613033625-fddfe03/master-haskell-20170613033625-fddfe03"
  version = 1
  sha1 = "0a9e91a8c3373a402c5f2c4fc8d9aabb210c03b3"

[build.dist]
  GHC_VERSION="7.10.2"
  CABAL_VERSION = "1.24.0.0"

[build.dist-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"
  CACHE = "true"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  PUBLISH_EXECUTABLES = "boris"

[build.branches-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"
  CACHE = "true"
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_BRANCHES"
  PUBLISH_EXECUTABLES = "boris"
